//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanhanga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_admin
    {
        public db_admin()
        {
            this.db_Category = new HashSet<db_Category>();
        }
    
        public int ad_id { get; set; }
        public string ad_username { get; set; }
        public string ad_password { get; set; }
    
        public virtual ICollection<db_Category> db_Category { get; set; }
    }
}
