//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanhanga.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdmarketingEntities : DbContext
    {
        public bdmarketingEntities()
            : base("name=bdmarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<db_admin> db_admin { get; set; }
        public DbSet<db_Category> db_Category { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tb_user> tb_user { get; set; }
    }
}
